[window]
opacity = 0.95
padding.x = 10
padding.y = 10

[font]
size = 11.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style= "Italic"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
